apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: python-mjwunpia
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/sjmrhtap/python-mjwunpia:d65011691e775c30d686ada358514690f4690a80@sha256:9224760e8d55f88223dd91e0385a244c365ef59c6518c6dc21dd39073e2b5a03
        name: container-image  
